### ISSUE TITLE
Drive D cannot be created.

### ISSUE THREAD

**Issue by yurylevin** [TotalJobsGroup/Packer#3]
Hello,

I have issue with drive D. I'm trying to use json similar to vmware.json but for Virtualbox. Creation of drive results in error:

    virtualbox-iso: new-partition : Not enough available capacity
    virtualbox-iso: At C:\Windows\Temp\script.ps1:16 char:5
    virtualbox-iso: +     new-partition -DriveLetter D -DiskNumber 0 -UseMaximum
Size

After that, image has only C drive, which is so large as I specify size in disk_size parameter inside json.

Do you know how to make it working (i.e. create C partition smaller than disk size)?

Thanks.

**Comment by Workshop2** [comment]
Hey @yurylevin,

You need to ensure in your "Autounattend.xml" your partition size is smaller than the disk defined in your "vmware.json" definition.

E.g. for our physical **disk** in [vmware.json](https://github.com/TotalJobsGroup/Packer/blob/master/vmware.json#L14) we specify 85GB(ish) and in our [Autounattend.xml](https://github.com/TotalJobsGroup/Packer/blob/master/answer_files/Autounattend.xml#L23) we specify 50GB for our **partition**

@yetanotherchris - any tips?

**Comment by yetanotherchris** [comment]
This happens sometimes with VMware/VBox, you just have to restart the base image and do a little rain dance...welcome the world of Windows server image building!
